server:
  port: 8088

weather:
  query:
    url: http://api.help.bj.cn/apis/weather6d/?id=101280601

spring:
  properties:
    mail:
      smtp:
        auth :true
        starttls:
          enable: true
          required :true
  mail:
    host:
    username:
    password:
